In [1]:
import numpy as np
np.__version__


'1.23.5'

In [2]:
#1# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
l =[0,1,2,3,4,5]
arr =np.array(l )
arr
type(arr)

numpy.ndarray

In [3]:
#2# Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5, 2.6, 3.7])
#
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


In [5]:
#3# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([2+5j,2+3j,3-4j])
type(arr.dtype)

numpy.dtype[complex128]

In [6]:
arr

array([2.+5.j, 2.+3.j, 3.-4.j])

In [7]:
arr=np.float32(np.float64(arr))
arr

/tmp/ipykernel_362/2326252065.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  arr=np.float32(np.float64(arr))


array([2., 2., 3.], dtype=float32)

In [8]:
#5# Given a NumPy array 'arr'
# with float64 data type, convert it to float32 to reduce decimal precision.
arr= np.array([2.5498,5.7629,6.8792])
arr=np.float32(np.float64(arr))
type(arr.dtype)


numpy.dtype[float32]

In [9]:
arr = (np.ceil(arr))
arr

array([3., 6., 7.], dtype=float32)

In [10]:
#6# Write a function array_attributes that takes a NumPy array as input
# and returns its shape, size, and data type.
arr=np.array([[3,4,6],[1,3,5],[7,9,8]])
arr.shape

(3, 3)

In [11]:
arr.size

9

In [12]:
type(arr.dtype)

numpy.dtype[int64]

In [13]:
#7# Create a function array_dimension that takes a NumPy array as input
# and returns its dimensionality
arr=np.array([[3,4,6],[1,3,5],[7,9,8]])
arr.ndim

2

In [14]:
arr=arr[np.newaxis,:]
arr.ndim

3

In [15]:
arr

array([[[3, 4, 6],
        [1, 3, 5],
        [7, 9, 8]]])

In [16]:
#8# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
#size in bytes.
arr=np.array([[3,4,6],[1,3,5],[7,9,8]])
arr

array([[3, 4, 6],
       [1, 3, 5],
       [7, 9, 8]])

In [17]:
arr.itemsize

8

In [18]:
arr.size

9

In [19]:
arr.itemsize * arr.size

72

In [20]:
#9#  Create a function array_strides that takes a NumPy array as input
# and returns the strides of the array
arr=np.arange(9).reshape([3,3])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr.strides

(24, 8)

In [22]:
#10# Design a function shape_stride_relationship that takes a NumPy array as input
#and returns the shape and strides of the array.
arr=np.array([[2,4,6,9],[6,8,4,6],[9,4,2,1]])
arr

array([[2, 4, 6, 9],
       [6, 8, 4, 6],
       [9, 4, 2, 1]])

In [23]:
arr.shape

(3, 4)

In [24]:
arr.strides

(32, 8)

In [25]:
#11#  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
#zeros with `n` elements.
import numpy as np
create_zeros_array = np.zeros(9)
create_zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
#12# Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
#NumPy array filled with ones of size `rows x cols`.
create_ones_matrix = np.ones((2, 3))
create_ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#13# Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

generate_range_array=np.arange(0, 10, 2)
generate_range_array

array([0, 2, 4, 6, 8])

In [28]:
#14# Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
generate_linear_space=np.linspace(1.5, 4.5, 3)
generate_linear_space

array([1.5, 3. , 4.5])

In [29]:
#15#  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`.
import numpy as np
arr2=np.eye(4,4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
#16# Write a function that takes a Python list and converts it into a NumPy array
list= [3,5,7,9]
type(list )

list

In [31]:
list1=np.array(list)
list1

array([3, 5, 7, 9])

In [32]:
type(list1)

numpy.ndarray

In [33]:
#17# Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
#same data.
A=np.array([2,4,6,8])
print("array :",A )

array : [2 4 6 8]


In [34]:
B=A.view()
print("view:",B)

view: [2 4 6 8]


In [35]:
#18# Write a function that takes two NumPy arrays and concatenates them along a specified axis.
x=np.array([2,3,4,5])
y=np.array([6,7,8,9])
z=np.concatenate ([x,y ])
z

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#19# Create two NumPy arrays with different shapes and concatenate
#them horizontally using `numpy concatenate             `.
import numpy as np
arr1=np.arange(9).reshape([3,3])
arr2=np.arange(12).reshape([3,4])
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
np.hstack([arr1,arr2 ])

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [39]:
#20# Write a function that vertically stacks multiple NumPy arrays given as a list.
arr1=np.arange(9).reshape([3,3])
arr2=np.arange(3).reshape([3,1])
arr2

array([[0],
       [1],
       [2]])

In [40]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr1 * arr2

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16]])

In [42]:
#21#  Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.
array = np.linspace(3, 9, 3)
array

array([3., 6., 9.])

In [43]:
#22# Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
array = np.linspace(0, 1, 10)
array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [44]:
#23#  Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

arr=np.logspace(1, 3, num=5)
arr

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [45]:
#24# Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
#are random integers between 1 and 100.
import numpy as np
import pandas as pd
data =np.random.randint(1,100, size =(5,3 ))
df= pd.DataFrame(data)
df

0   1   2
0  50  54  21
1  66  41   1
2  74  37   7
3  71  31  86
4  29  28  32

In [46]:
#25# Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame
data =np.random.randint(-1,10, size =(5,3 ))
df= pd.DataFrame(data)
df


0  1  2
0  4  8  2
1 -1  2  9
2  9  2  5
3 -1 -1 -1
4  7 -1  3

In [47]:
df.replace(-1,0)

0  1  2
0  4  8  2
1  0  2  9
2  9  2  5
3  0  0  0
4  7  0  3

In [48]:
#26# Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [49]:
arr[2]

30

In [50]:
#27# Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
(arr_2d[0,])

array([1, 2, 3])

In [52]:
(arr_2d[1,])

array([4, 5, 6])

In [53]:
#28# Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#arr = np.array([3, 8, 2, 10, 5, 7])
arr = np.array([3,8,2,10,5,7])
arr

array([ 3,  8,  2, 10,  5,  7])

In [54]:
arr<5

array([ True, False,  True, False, False, False])

In [55]:
#29# Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
(arr[2:6])

array([3, 4, 5, 6])

In [56]:
#30# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [58]:
#31# Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array

arr_1=np.array([7,2,4,6,8,9])
indices =np.array([0,2,4])
np.take(arr_1,indices)


array([7, 4, 8])

In [59]:
#32# Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# boolean indexing
arr_A= np.array([23,3,7,45,8,16,9,5,40])
arr_A>10

array([ True, False, False,  True, False,  True, False, False,  True])

In [60]:
#33# Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#separate arrays for each dimension.
arr_3d=np.array([[[3,5,7],[4,6,8],[1,3,9]],[[2,3,6],[3,4,7],[4,5,8]]])
arr_3d

array([[[3, 5, 7],
        [4, 6, 8],
        [1, 3, 9]],

       [[2, 3, 6],
        [3, 4, 7],
        [4, 5, 8]]])

In [61]:
arr_3d[:1,0:2,0:2]

array([[[3, 5],
        [4, 6]]])

In [62]:
#34# Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing.
import numpy as np
np.fromfunction(lambda i,j :i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
#35#Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.
arr_in=np.arange(20).reshape(4,5)
arr_in

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
ind=np.array([[0,2],[1,3]])
ind

array([[0, 2],
       [1, 3]])

In [65]:
arr_in[ind[:,0],ind[:,1]]

array([2, 8])

In [66]:
#36# Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np
arr1=np.arange(9).reshape([3,3])
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
arr1 +5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [68]:
#37# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting
arr1=np.arange(3).reshape(1,3)
arr2=np.arange(12).reshape(3,4)
arr1.T *arr2

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [69]:
#38# Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
#NumPy broadcasting
arr1 =np  .array([2,4,6,8])
arr2=np.array([[3,4,5,6],[1,3,5,7],[0,1,2,3]])
arr1 + arr2

array([[ 5,  8, 11, 14],
       [ 3,  7, 11, 15],
       [ 2,  5,  8, 11]])

In [70]:
#39# Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
# broadcasting
arr1 =np.random.randint(1,4,(3,1))
arr2  =np.random.randint(1,4,(1,3))
arr1  + arr2

array([[2, 3, 4],
       [2, 3, 4],
       [4, 5, 6]])

In [71]:
#40# Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.
import numpy as np
arr1 =np.random.randint(1,9,(2,3))
arr2  =np.random.randint(1,9,(2,2))
arr3=np.reshape(arr1,(3,2))
print(arr1,arr2,arr3)

[[2 7 8]
 [8 8 5]] [[3 1]
 [3 4]] [[2 7]
 [8 8]
 [8 5]]


In [72]:
arr3 @arr2

array([[27, 30],
       [48, 40],
       [39, 28]])

In [73]:
#41# Calculate column wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

In [74]:
#42# Find maximum value in each row of the given array
# arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)

array([3, 6])

In [75]:
#43# For the given array, find indices of maximum value in each column
# arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_index=arr .argmax(0)
arr_index

array([1, 1, 1])

In [76]:
#44# For the given array, apply custom function to calculate moving sum along rows
# arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(arr,axis=1)

array([ 6, 15])

In [77]:
#45# In the given array, check if all elements in each column are even
#arr = np.array([[2, 4, 6], [3, 5, 7]])
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr1 = arr[arr % 2 ==0]
arr1

array([2, 4, 6])

In [78]:
b=arr % 2 == 0
b

array([[ True,  True,  True],
       [False, False, False]])

In [79]:
#46# Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
#reshaped matrix.
#original_array = np.array([1, 2, 3, 4, 5, 6])
original_array = np.array([1, 2, 3, 4, 5, 6])
arr =np.reshape(original_array,(2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
#47# Create a function that takes a matrix as input and returns the flattened array
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix.flatten()

array([1, 2, 3, 4, 5, 6])

In [81]:
#48# Write a function that concatenates two given arrays along a specified axis.
#array1 = np.array([[1, 2], [3, 4]])
#array2 = np.array([[5, 6], [7, 8]])
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array1+array2

array([[ 6,  8],
       [10, 12]])

In [82]:
#49# Create a function that splits an array into multiple sub-arrays along a specified axis
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.hsplit(original_array,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [83]:
#50# Write a function that inserts and then deletes elements from a given array at specified indices.
#original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]
original_array=np.array([1,2,3,4,5])
arr=np.insert(original_array,1,10)
arr1=np.insert(arr ,3,11)
arr2=np.delete (arr1,0)
array=np.delete(arr2,3)
array

array([10,  2, 11,  4,  5])

In [84]:
#51# Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#Perform element-wise addition between `arr1` and `arr2`.

arr1=np.arange(5)
arr2=np.random.randint(1,10,5)
print(arr1,arr2)

[0 1 2 3 4] [3 7 6 6 3]


In [85]:
arr1 + arr2

array([3, 8, 8, 9, 7])

In [86]:
#52# Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.
import numpy as np
arr1=np.array([10,9,8,7,6,5,4,3,2,1])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1,arr2)

[10  9  8  7  6  5  4  3  2  1] [ 1  2  3  4  5  6  7  8  9 10]


In [87]:
np.subtract(arr2,arr1)

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

In [91]:
#53# Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.
arr1=np.arange(5)
arr2=np.random.randint(1,5,5)
print(arr1,arr2)

[0 1 2 3 4] [3 3 3 2 2]


In [92]:
arr1 * arr2

array([0, 3, 6, 6, 8])

In [93]:
#54#  Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.
arr1=np.arange(2,11,2)
arr2=np.random.randint(1,5,5)
print(arr1,arr2)

[ 2  4  6  8 10] [2 2 2 2 1]


In [94]:
arr1 / arr2

array([ 1.,  2.,  3.,  4., 10.])

In [95]:
#55# Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise
arr1=np.random.randint(1,5,5)
arr2=np.flip(arr1)
print(arr1,arr2)

[2 3 2 4 2] [2 4 2 3 2]


In [96]:
arr1=np.power(arr1,arr2)
arr1

array([ 4, 81,  4, 64,  4])

In [97]:
np.exp(arr1)

array([5.45981500e+01, 1.50609731e+35, 5.45981500e+01, 6.23514908e+27,
       5.45981500e+01])

In [98]:
#56# Write a function that counts the occurrences of a specific substring within a NumPy array of strings
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
np.char.count(arr,'hello')

array([1, 0, 1, 0, 1])

In [99]:
#57# Write a function that extracts uppercase characters from a NumPy array of strings.
#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
ARR

In [100]:
#58#  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr1=np.array(['orange','mango'])
np.append(arr,arr1)

array(['apple', 'banana', 'grape', 'pineapple', 'orange', 'mango'],
      dtype='<U9')

In [101]:
#59# Write a function that concatenates strings in a NumPy array element-wise
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.concatenate((arr1,arr2),axis=0)

array(['Hello', 'World', 'Open', 'AI'], dtype='<U5')

In [102]:
#60# Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(max(arr, key=len))

pineapple


In [103]:
#61# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.
arr=np.random.randint(1,1000,100)
arr

array([666, 361, 919, 644, 779, 979, 479, 716, 667, 713, 608, 254, 708,
       209, 926, 656, 211, 643, 838, 337, 405, 811, 620, 188, 211, 531,
       551, 844, 414, 735, 886, 118, 549,  97, 722, 509, 414, 923, 501,
       285, 672, 373, 719, 516,  25, 274, 211, 557, 800, 325, 118,  48,
       757, 884, 736, 565, 354, 198, 820, 400, 645, 775, 339, 188, 480,
        91, 605, 907, 100, 442, 584, 202, 917, 495, 131, 869, 294, 312,
       910, 662, 764, 679, 596, 448, 500, 339, 314, 551, 686, 808, 457,
       256, 559, 155, 892, 249, 478, 467,  94, 785])

In [104]:
np.mean(arr)

520.04

In [105]:
np.median(arr)

540.0

In [106]:
np.var(arr)

64314.258400000006

In [107]:
np.std(arr)

253.60255992398817

In [108]:
#62# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr1=np.random.randint(1,100,50)
arr1

array([ 4, 62, 26,  6, 59, 11, 77, 78, 92, 67, 92, 40, 83, 34, 82, 29, 72,
       65, 77, 60, 38, 21, 69, 79,  8, 48, 94, 54,  8, 12, 44, 58, 64, 66,
       96,  1, 63, 64, 70, 64, 29, 19,  2, 96, 98, 70,  3, 10, 21, 49])

In [109]:
np.percentile(arr1,25)

22.25

In [110]:
np.percentile(arr1,75)

71.5

In [111]:
#63# Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
rng = np.random.default_rng(seed=42)
xarr = rng.random((3, 3))
xarr

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [112]:
yarr = rng.random((3, 3))
yarr

array([[0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 ],
       [0.22723872, 0.55458479, 0.06381726]])

In [113]:
R2 = np.corrcoef(xarr, yarr)
R2

array([[ 1.        ,  0.99256089, -0.68080986,  0.75008178, -0.934284  ,
        -0.99004057],
       [ 0.99256089,  1.        , -0.76492172,  0.82502011, -0.97074098,
        -0.99981569],
       [-0.68080986, -0.76492172,  1.        , -0.99507202,  0.89721355,
         0.77714685],
       [ 0.75008178,  0.82502011, -0.99507202,  1.        , -0.93657855,
        -0.83571711],
       [-0.934284  , -0.97074098,  0.89721355, -0.93657855,  1.        ,
         0.97517215],
       [-0.99004057, -0.99981569,  0.77714685, -0.83571711,  0.97517215,
         1.        ]])

In [114]:
#63#
arr=np.random.randint(1,5,9)
arr

array([2, 1, 4, 1, 3, 4, 4, 4, 4])

In [115]:
arr1=np.random.randint(50,100,9)
arr1

array([84, 61, 63, 83, 60, 88, 71, 71, 76])

In [116]:
R2 = np.corrcoef(arr, arr1)
R2

array([[ 1.        , -0.02708976],
       [-0.02708976,  1.        ]])

In [117]:
#64# Create two matrices and perform matrix multiplication using NumPy's `dot` function.
a=np.matrix([[1, 2], [3, 4]])
b=np.matrix([[5, 6], [7, 8]])
np.dot(a,b)

matrix([[19, 22],
        [43, 50]])

In [118]:
#65# Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.
arr=np.random.randint(10,1000,50)
arr

array([751, 703, 168, 396, 162, 563, 871, 295, 652, 495,  25, 823,  56,
       535, 174, 863, 740,  47, 589,  29, 680, 364, 378, 586, 601, 581,
       589, 879, 767, 199,  59, 471, 850, 567, 594, 486, 943, 277, 959,
       952, 400, 866, 453, 340, 985, 388, 544, 480, 364, 969])

In [119]:
#66# Create a NumPy array of integers and find the index of a specific element.
a = np.array([1, 2, 3, 4, 8, 6, 7, 3, 9, 10])
print("All index value of 3 is: ", np.where(a == 3)[0])

All index value of 3 is:  [2 7]


In [120]:
#67# Generate a random NumPy array and sort it in ascending order.
T = np.random.randint(1,10, 10)
T

array([2, 9, 5, 8, 5, 2, 7, 2, 7, 2])

In [121]:
np.sort(T)

array([2, 2, 2, 2, 5, 5, 7, 7, 8, 9])

In [122]:
#68# Filter elements >20  in the given NumPy array
# arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
arr[(arr > 20)]

array([25, 42, 30])

In [123]:
#69# Filter elements which are divisible by 3 from a given NumPy array
# arr = np.array([1, 5, 8, 12, 15])
arr = np.array([1, 5, 8, 12, 15])
A=(arr%3==0)
print(arr[A])

[12 15]


In [124]:
#70#  Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
# arr = np.array([10, 20, 30, 40, 50])
arr = np.array([10, 20, 30, 40, 50])

In [125]:
#71# For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])
arr = np.array([1, 2, 3])
type(arr.dtype).byteorder


<member 'byteorder' of 'numpy.dtype' objects>

In [126]:
type(arr.dtype)

numpy.dtype[int64]

In [127]:
#72# For the given NumPy array, perform byte swapping in place using `byteswap()`
# arr = np.array([1, 2, 3], dtype=np.int32)
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [128]:
#73# For the given NumPy array, swap its byte order without modifying the original array using
# `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [129]:
#74#  For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.byteswap(True))

[16777216 33554432 50331648]


In [130]:
#75#  For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)

int32


In [131]:
#76# Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1=np.random.randint(1,10,5)
arr1

array([3, 1, 7, 5, 3])

In [132]:
copy_arr=arr1.copy()
copy_arr

array([3, 1, 7, 5, 3])

In [133]:
copy_arr[3]=5
print(arr1,copy_arr)

[3 1 7 5 3] [3 1 7 5 3]


In [134]:
#77#  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix=np.array([[2, 4, 6], [6, 8, 10],[3,7,9]])
matrix

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 3,  7,  9]])

In [135]:
view_slice=(matrix[2,0:3])
view_slice

array([3, 7, 9])

In [136]:
view_slice[1]=1
print(matrix,view_slice)

[[ 2  4  6]
 [ 6  8 10]
 [ 3  1  9]] [3 1 9]


In [137]:
#78# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,2]])
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  2]])

In [138]:
view_b=(array_a[1,1:3])
view_b

array([5, 6])

In [139]:
view_b + 5

array([10, 11])

In [140]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  2]])

In [141]:
#79# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.
orig_array= np.arange(0,8).reshape(2, 4)
orig_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [142]:
reshape_view=orig_array.reshape(4, 2)
reshape_view

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [143]:
reshape_view[0]=9
print(orig_array,reshape_view)

[[9 9 2 3]
 [4 5 6 7]] [[9 9]
 [2 3]
 [4 5]
 [6 7]]


In [144]:
#80# Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data =np.random.randint(1,15,12).reshape(3, 4)
data

array([[12,  8,  5, 10],
       [10,  1, 13,  4],
       [ 2,  1,  4,  9]])

In [145]:
data_copy = np.copy(data)
data_copy[data>5]


array([12,  8, 10, 10, 13,  9])

In [146]:
data_copy[1]=12
data_copy

array([[12,  8,  5, 10],
       [12, 12, 12, 12],
       [ 2,  1,  4,  9]])

In [147]:
data

array([[12,  8,  5, 10],
       [10,  1, 13,  4],
       [ 2,  1,  4,  9]])

In [148]:
#81# Create two matrices A and B of identical shape containing integers and perform addition and subtraction
#operations between them.
A = ([1,2,3], [4,5,6])
B = ([7,8,9])
print(A,B)

([1, 2, 3], [4, 5, 6]) [7, 8, 9]


In [149]:
np.add(A,B)

array([[ 8, 10, 12],
       [11, 13, 15]])

In [150]:
np.subtract(A,B)

array([[-6, -6, -6],
       [-3, -3, -3]])

In [151]:
#82#  Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.arange(2,8).reshape(3, 2)
C

array([[2, 3],
       [4, 5],
       [6, 7]])

In [152]:
D = np.arange(2,10).reshape(2, 4)
D

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [153]:
np.dot(C,D)

array([[22, 27, 32, 37],
       [38, 47, 56, 65],
       [54, 67, 80, 93]])

In [154]:
#83# Create a matrix `E` and find its transpose
a= np.array([[1, 2], [4, 5], [7, 8]])
a

array([[1, 2],
       [4, 5],
       [7, 8]])

In [155]:
a.T

array([[1, 4, 7],
       [2, 5, 8]])

In [156]:
 #84# Generate a square matrix `F` and compute its determinant.
F= np.array([[6, 1],
              [4, -2]])
print(np.linalg.det(F))

-15.999999999999998


In [157]:
#85#  Create a square matrix `G` and find its inverse.
G= np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(G))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
